"""empty message

Revision ID: 4d3e53d46b8e
Revises: 5b1c0249e535
Create Date: 2017-04-08 12:07:10.415002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3e53d46b8e'
down_revision = '5b1c0249e535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_nickname', table_name='user')
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=1)
    # ### end Alembic commands ###
